from NSController import Controller
import datetime

ctr = Controller()

# Cursor on SystemSettings-->System-->Date and Time-->Date and Time
# 先触发vs断网跳帧的bug，然后进入设置-->主机-->日期与时间-->现在的日期与时间，光标停留在日期和时间上

#Input current date of your Switch 输入当前日期
currentDate= datetime.date(2020,2,21) # input date(year,month,day) 输入switch机器当前日期(年，月，日)
frames_num = 99 # Number of frames to go forward  需前进帧数


# Reset Cursor 光标复位
def resetCursor():
    ctr.A()
    ctr.r()
    ctr.r()
    ctr.r()
    ctr.r()
    ctr.r()
    ctr.A()
resetCursor()
prev_year = currentDate.year
prev_mon = currentDate.month
prev_day = currentDate.day

for i in range(1,frames_num+1):
    print('下个日期:' + currentDate.strftime("%Y-%m-%d"))
    print(i)
    if (i>1 and (i-1)%200 == 0):  # save every 200 frames
        if(currentDate.year == prev_year):
            if(currentDate.month == prev_mon):
                if(currentDate.day != prev_day):
                    # day+1
                    ctr.A()
                    ctr.l()
                    ctr.l()
                    ctr.l()
                    ctr.u()
                    ctr.r()
                    ctr.r()
                    ctr.r()
                    ctr.A()
                    # save game
                    ctr.h()
                    ctr.pause(2)
                    ctr.A()
                    ctr.pause(2)
                    ctr.X()
                    ctr.pause(2)
                    ctr.R()
                    ctr.pause(2)
                    ctr.A()
                    print('正在保存游戏...')
                    ctr.pause(5)
                    print('----------已保存游戏----------')
                    ctr.h()
                    ctr.pause(1)
                    ctr.d()
                    ctr.r()
                    ctr.r()
                    ctr.r()
                    ctr.r()
                    ctr.A()
                    ctr.pause(1)
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.r()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    ctr.A()
                    ctr.d()
                    ctr.d()
                    ctr.d()
                    resetCursor()
            else:
                # day+1
                ctr.A()
                ctr.l()
                ctr.l()
                ctr.l()
                ctr.u()
                # mon+1
                ctr.l()
                ctr.u()
                ctr.r()
                ctr.r()
                ctr.r()
                ctr.r()
                ctr.A()
                # save game
                ctr.h()
                ctr.pause(2)
                ctr.A()
                ctr.pause(2)
                ctr.X()
                ctr.pause(2)
                ctr.R()
                ctr.pause(2)
                ctr.A()
                print('正在保存游戏...')
                ctr.pause(5)
                print('----------已保存游戏----------')
                ctr.h()
                ctr.pause(1)
                ctr.d()
                ctr.r()
                ctr.r()
                ctr.r()
                ctr.r()
                ctr.A()
                ctr.pause(1)
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.r()
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.d()
                ctr.A()
                ctr.d()
                ctr.d()
                ctr.d()
                resetCursor()
        else:
            # day+1
            ctr.A()
            ctr.l()
            ctr.l()
            ctr.l()
            ctr.u()
            # mon+1
            ctr.l()
            ctr.u()
            # year+1
            ctr.l()
            ctr.u()
            ctr.r()
            ctr.r()
            ctr.r()
            ctr.r()
            ctr.r()
            ctr.A()
            # save game
            ctr.h()
            ctr.pause(2)
            ctr.A()
            ctr.pause(2)
            ctr.X()
            ctr.pause(2)
            ctr.R()
            ctr.pause(2)
            ctr.A()
            print('正在保存游戏...')
            ctr.pause(5)
            print('----------已保存游戏----------')
            ctr.h()
            ctr.pause(1)
            ctr.d()
            ctr.r()
            ctr.r()
            ctr.r()
            ctr.r()
            ctr.A()
            ctr.pause(1)
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.r()
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.d()
            ctr.A()
            ctr.d()
            ctr.d()
            ctr.d()
            resetCursor()
        print('已跳' + str(i) + '帧')
        prev_year = currentDate.year
        prev_mon = currentDate.month
        prev_day = currentDate.day
        print('当前日期:' + currentDate.strftime("%Y-%m-%d"))
        currentDate = currentDate + datetime.timedelta(days=1)
    else:
        if (currentDate.year == prev_year):
            if (currentDate.month == prev_mon):
                if (currentDate.day != prev_day):
                    # day+1
                    ctr.A()
                    ctr.l()
                    ctr.l()
                    ctr.l()
                    ctr.u()
                    ctr.r()
                    ctr.r()
                    ctr.r()
                    ctr.A()
            else:
                # day+1
                ctr.A()
                ctr.l()
                ctr.l()
                ctr.l()
                ctr.u()
                # mon+1
                ctr.l()
                ctr.u()
                ctr.r()
                ctr.r()
                ctr.r()
                ctr.r()
                ctr.A()
        else:
            # day+1
            ctr.A()
            ctr.l()
            ctr.l()
            ctr.l()
            ctr.u()
            # mon+1
            ctr.l()
            ctr.u()
            # year+1
            ctr.l()
            ctr.u()
            ctr.r()
            ctr.r()
            ctr.r()
            ctr.r()
            ctr.r()
            ctr.A()
        print('已跳' + str(i) + '帧')
        prev_year = currentDate.year
        prev_mon = currentDate.month
        prev_day = currentDate.day
        print('当前日期:' + currentDate.strftime("%Y-%m-%d"))
        currentDate = currentDate + datetime.timedelta(days=1)
print('******已结束******')
ctr.close()